# Generated by Django 4.2.29 on 2026-09-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardamomVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('optimal_altitude', models.CharField(blank=True, max_length=100, null=True)),
                ('yield_potential_kg_acre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cardamom_varieties',
            },
        ),
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('buyer_name', models.CharField(max_length=150)),
                ('destination_country', models.CharField(max_length=100)),
                ('cardamom_variety', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date', models.DateField()),
                ('status', models.CharField(default='PROCESSING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'export_orders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('FARMER', 'Farmer'), ('TRADER', 'Trader'), ('EXPORTER', 'Exporter'), ('ADMIN', 'Admin')], max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='UPI / Bank Transfer', max_length=50)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='iam.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='iam.user')),
            ],
            options={
                'db_table': 'transaction_records',
            },
        ),
        migrations.CreateModel(
            name='ShipmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(max_length=100)),
                ('status', models.CharField(default='IN_TRANSIT', max_length=30)),
                ('origin', models.CharField(default='Cochin Port, India', max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('dispatch_date', models.DateField()),
                ('estimated_delivery', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='iam.exportorder')),
            ],
            options={
                'db_table': 'shipment_records',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardamom_variety', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField()),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_as_buyer', to='iam.user')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_as_farmer', to='iam.user')),
            ],
            options={
                'db_table': 'sale_records',
            },
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('variety', models.CharField(default='Njallani Green Gold', max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantations', to='iam.user')),
            ],
            options={
                'db_table': 'plantations',
            },
        ),
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(default='SYSTEM', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='iam.user')),
            ],
            options={
                'db_table': 'notification_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('water_volume_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irrigation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='iam.user')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='iam.plantation')),
            ],
            options={
                'db_table': 'irrigation_records',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('grade', models.CharField(default='AGEB 8mm', max_length=50)),
                ('status', models.CharField(default='IN_STOCK', max_length=30)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='iam.user')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('fresh_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dried_quantity_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('variety', models.CharField(max_length=100)),
                ('grade', models.CharField(default='8mm Bold', max_length=50)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='iam.user')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='iam.plantation')),
            ],
            options={
                'db_table': 'harvest_records',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.AddField(
            model_name='exportorder',
            name='exporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_orders', to='iam.user'),
        ),
        migrations.CreateModel(
            name='ExportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='VERIFIED', max_length=30)),
                ('issued_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='iam.exportorder')),
            ],
            options={
                'db_table': 'export_documents',
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='iam.user')),
                ('plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.plantation')),
            ],
            options={
                'db_table': 'expense_records',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='iam.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgrochemicalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('FERTILIZER', 'Fertilizer'), ('PESTICIDE', 'Pesticide')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('application_date', models.DateField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrochemical_usages', to='iam.user')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrochemical_usages', to='iam.plantation')),
            ],
            options={
                'db_table': 'agrochemical_usages',
            },
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='iam.user')),
            ],
            options={
                'db_table': 'user_identities',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
