# Generated by Django 4.2.29 on 2026-09-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('available_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grade', models.CharField(default='8mm Bold', max_length=50)),
                ('status', models.CharField(default='AVAILABLE', max_length=30)),
                ('available_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='iam.user')),
                ('harvest_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.harvestrecord')),
                ('plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.plantation')),
            ],
            options={
                'db_table': 'marketplace_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('available_quantity_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('requested_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests_as_farmer', to='iam.user')),
                ('marketplace_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='iam.marketplacelisting')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests_as_trader', to='iam.user')),
            ],
            options={
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('variety', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('full_dry_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_cycles', to='iam.user')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_cycles', to='iam.plantation')),
            ],
            options={
                'db_table': 'harvest_cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_supplies_as_exporter', to='iam.user')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_supplies_as_trader', to='iam.user')),
            ],
            options={
                'db_table': 'export_supply_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='harvest_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='iam.harvestcycle'),
        ),
    ]
