# Generated by Django 4.2.29 on 2026-10-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_marketplacelisting_purchaserequest_harvestcycle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='exportorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shipmentrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='agrochemicalusage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='agrochemicalusage',
            name='next_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportdocument',
            name='document_name',
            field=models.CharField(default='Document', max_length=255),
        ),
        migrations.AddField(
            model_name='exportdocument',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='destination_port',
            field=models.CharField(default='Dubai Port', max_length=100),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='expected_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='grade',
            field=models.CharField(default='AGEB 8mm', max_length=50),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='incoterms',
            field=models.CharField(default='FOB', max_length=50),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.inventoryitem'),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='payment_method',
            field=models.CharField(default='BANK_TRANSFER', max_length=50),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='shipment_method',
            field=models.CharField(default='SEA', max_length=50),
        ),
        migrations.AddField(
            model_name='exportorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='expected_supply_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='grade',
            field=models.CharField(default='AGEB 8mm', max_length=50),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_supplies', to='iam.inventoryitem'),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Pay Online'), ('DIRECT', 'Pay Directly')], default='ONLINE', max_length=30),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportsupplyrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='plantation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.plantation'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='source_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_inventories', to='iam.user'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='source_trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader_supplied_inventories', to='iam.user'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plantation',
            name='number_of_plants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='grade',
            field=models.CharField(default='8mm Bold', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='handover_confirmed_by_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Pay Online'), ('DIRECT', 'Pay Directly')], default='ONLINE', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='pickup_confirmed_by_trader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='pickup_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_PICKUP', 'Ready For Pickup'), ('PICKUP_CONFIRMED', 'Pickup Confirmed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='plantation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.plantation'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='ready_for_pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='grade',
            field=models.CharField(default='8mm Bold', max_length=50),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='plantation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.plantation'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipmentrecord',
            name='shipping_method',
            field=models.CharField(default='SEA', max_length=50),
        ),
        migrations.AlterField(
            model_name='exportorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('QUALITY_CHECK', 'Quality Check'), ('QUALITY_APPROVED', 'Quality Approved'), ('QUALITY_REJECTED', 'Quality Rejected'), ('PACKAGING', 'Packaging'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('READY_FOR_SHIPMENT', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30),
        ),
        migrations.AlterField(
            model_name='exportsupplyrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('READY_FOR_RECEIPT', 'Ready For Receipt'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('READY_FOR_PICKUP', 'Ready For Pickup'), ('PICKUP_CONFIRMED', 'Pickup Confirmed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentrecord',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('READY_FOR_SHIPMENT', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered')], default='PREPARING', max_length=30),
        ),
        migrations.CreateModel(
            name='QualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('moisture_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('size_mm', models.CharField(default='8mm', max_length=50)),
                ('color_appearance', models.CharField(default='Deep Green', max_length=100)),
                ('quality_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=30)),
                ('inspection_date', models.DateField()),
                ('inspector_name', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_records', to='iam.exportorder')),
            ],
            options={
                'db_table': 'quality_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(default='Vacuum Pack', max_length=100)),
                ('number_of_packages', models.IntegerField()),
                ('weight_per_package_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_records', to='iam.exportorder')),
            ],
            options={
                'db_table': 'packaging_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternationalBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_buyers', to='iam.user')),
            ],
            options={
                'db_table': 'international_buyers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exportorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_orders', to='iam.internationalbuyer'),
        ),
    ]
