# Generated by Django 4.2.29 on 2026-10-08 04:20

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin(apps, schema_editor):
    User = apps.get_model('iam', 'User')
    if not User.objects.filter(email='admin@cardalink.com').exists():
        User.objects.create(
            full_name='System Admin',
            email='admin@cardalink.com',
            phone='1234567890',
            role='ADMIN',
            status='APPROVED',
            is_verified=True,
            password_hash=make_password('Admin@1234')
        )

class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_alter_exportdocument_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
