PERMISSIONS = {
    # Farmer Permissions
    'VIEW_OWN_PLANTATION': 'VIEW_OWN_PLANTATION',
    'MANAGE_OWN_PLANTATION': 'MANAGE_OWN_PLANTATION',
    'RECORD_HARVEST': 'RECORD_HARVEST',
    'MANAGE_INVENTORY': 'MANAGE_INVENTORY',
    'MANAGE_EXPENSES': 'MANAGE_EXPENSES',
    'CREATE_SALES': 'CREATE_SALES',

    # Trader Permissions
    'VIEW_MARKETPLACE': 'VIEW_MARKETPLACE',
    'VIEW_CARDAMOM': 'VIEW_CARDAMOM',
    'CREATE_PURCHASE': 'CREATE_PURCHASE',
    'VIEW_TRANSACTIONS': 'VIEW_TRANSACTIONS',
    'EXPORT_SUPPLY': 'EXPORT_SUPPLY',
    'VIEW_REPORTS': 'VIEW_REPORTS',

    # Exporter Permissions
    'MANAGE_EXPORT_ORDERS': 'MANAGE_EXPORT_ORDERS',
    'MANAGE_DOCUMENTS': 'MANAGE_DOCUMENTS',
    'MANAGE_SHIPMENTS': 'MANAGE_SHIPMENTS',

    # Admin Permissions
    'MANAGE_USERS': 'MANAGE_USERS',
    'APPROVE_USERS': 'APPROVE_USERS',
    'MANAGE_FARMERS': 'MANAGE_FARMERS',
    'MANAGE_TRADERS': 'MANAGE_TRADERS',
    'MANAGE_EXPORTERS': 'MANAGE_EXPORTERS',
    'VIEW_SYSTEM_DATA': 'VIEW_SYSTEM_DATA',
}

ROLE_PERMISSIONS = {
    'FARMER': [
        PERMISSIONS['VIEW_OWN_PLANTATION'],
        PERMISSIONS['MANAGE_OWN_PLANTATION'],
        PERMISSIONS['RECORD_HARVEST'],
        PERMISSIONS['MANAGE_INVENTORY'],
        PERMISSIONS['MANAGE_EXPENSES'],
        PERMISSIONS['CREATE_SALES'],
    ],
    'TRADER': [
        PERMISSIONS['VIEW_MARKETPLACE'],
        PERMISSIONS['VIEW_CARDAMOM'],
        PERMISSIONS['CREATE_PURCHASE'],
        PERMISSIONS['MANAGE_INVENTORY'],
        PERMISSIONS['VIEW_TRANSACTIONS'],
        PERMISSIONS['CREATE_SALES'],
        PERMISSIONS['EXPORT_SUPPLY'],
        PERMISSIONS['VIEW_REPORTS'],
    ],

    'EXPORTER': [
        PERMISSIONS['MANAGE_EXPORT_ORDERS'],
        PERMISSIONS['MANAGE_DOCUMENTS'],
        PERMISSIONS['MANAGE_SHIPMENTS'],
        PERMISSIONS['MANAGE_INVENTORY'],
    ],
    'ADMIN': [
        PERMISSIONS['MANAGE_USERS'],
        PERMISSIONS['APPROVE_USERS'],
        PERMISSIONS['MANAGE_FARMERS'],
        PERMISSIONS['MANAGE_TRADERS'],
        PERMISSIONS['MANAGE_EXPORTERS'],
        PERMISSIONS['VIEW_SYSTEM_DATA'],
        PERMISSIONS['MANAGE_INVENTORY'],
        PERMISSIONS['VIEW_MARKETPLACE'],
        PERMISSIONS['MANAGE_EXPORT_ORDERS'],
    ],
}

def get_permissions_for_role(role):
    if not role:
        return []
    return ROLE_PERMISSIONS.get(role.upper(), [])
